### ISSUE TITLE
Cannot read Packet DeclareCommands

### ISSUE THREAD

**Issue by psu-de** [psu-de/MineSharp#12]
When I updated minecraft-data to the latest version, and regenerated the source files, the following error occures when starting the bot:

```
[ERROR][16:43:44][Protocol  ] > Error reading packet!
[ERROR][16:43:44][Protocol  ] > System.Exception: Invalid value: 'minecraft:nbt_tag'
   at MineSharp.Data.Protocol.CommandNode.ExtraNodeDataSwitch.ExtraNodeDataSwitchState2Container.PropertiesSwitch.Read(PacketBuffer buffer, String state) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 1738
   at MineSharp.Data.Protocol.CommandNode.ExtraNodeDataSwitch.ExtraNodeDataSwitchState2Container.<>c__DisplayClass20_0.<Read>b__2(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 1803
   at MineSharp.Data.Protocol.CommandNode.ExtraNodeDataSwitch.ExtraNodeDataSwitchState2Container.Read(PacketBuffer buffer, FlagsBitfield flags) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 1803
   at MineSharp.Data.Protocol.CommandNode.ExtraNodeDataSwitch.<>c__DisplayClass8_0.<Read>b__2(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 1824
   at MineSharp.Data.Protocol.CommandNode.ExtraNodeDataSwitch.Read(PacketBuffer buffer, Byte state, FlagsBitfield flags) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 1824
   at MineSharp.Data.Protocol.CommandNode.<>c__DisplayClass21_0.<Read>b__3(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 1854
   at MineSharp.Data.Protocol.CommandNode.Read(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 1854
   at MineSharp.Data.Protocol.Play.Clientbound.PacketDeclareCommands.<>c.<Read>b__10_3(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 4091
   at MineSharp.Data.Protocol.PacketBuffer.ReadArray[T](Int32 length, Func`2 reader) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 255
   at MineSharp.Data.Protocol.Play.Clientbound.PacketDeclareCommands.<>c.<Read>b__10_0(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 4091
   at MineSharp.Data.Protocol.Play.Clientbound.PacketDeclareCommands.Read(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 4091
   at MineSharp.Data.Protocol.Play.Clientbound.Packet.ParamsSwitch.<>c.<Read>b__6_15(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 7301
   at MineSharp.Data.Protocol.Play.Clientbound.Packet.ParamsSwitch.Read(PacketBuffer buffer, String state) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 7301
   at MineSharp.Data.Protocol.Play.Clientbound.Packet.<>c__DisplayClass11_0.<Read>b__1(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 7615
   at MineSharp.Data.Protocol.Play.Clientbound.Packet.Read(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 7615
   at MineSharp.Data.Protocol.Play.Clientbound.PlayPacketFactory.ReadPacket(PacketBuffer buffer) in D:\MineSharp\Data\MineSharp.Data\Protocol.cs:line 7621
   at MineSharp.Protocol.PacketFactory.BuildPacket(Byte[] data, Int32 uncompressedLength) in D:\MineSharp\Components\MineSharp.Protocol\PacketFactory.cs:line 74
```

**Comment by psu-de** [comment]
Fixed after updating minecraft-data
