### ISSUE TITLE
Bot does not connect

### ISSUE THREAD

**Issue by Apocritas99** [psu-de/MineSharp#75]
tried every version offline and online
```
2024-08-15 12:19:18.2051|DEBUG|MineSharp.Protocol.MinecraftClient|Connecting to 127.0.0.1:25565.
2024-08-15 12:19:18.2051|INFO|MineSharp.Protocol.MinecraftClient|Connected, starting handshake...
2024-08-15 12:19:18.4425|DEBUG|MineSharp.Protocol.MinecraftStream|Enabling encryption.
2024-08-15 12:19:20.3564|ERROR|MineSharp.Data.Protocol.ProtocolData|Failed to get PacketType for: flow = Clientbound, state = Login, id = 118
```

**Comment by psu-de** [comment]
Hi,
what server brand are you using? And are you using the nuget package or a clone of this repository?

**Comment by Klotzi111** [comment]
What version is the minecraft server?

From the line `Failed to get PacketType for: flow = Clientbound, state = Login, id = 118` I can tell it is MC 1.20.6 or higher. Because in older versions there is no packet with such an high id `118 (0x76)`.
The repo's README says `Supported Versions: 1.18.x - 1.20.4`

**Comment by Apocritas99** [comment]
i was in version 1.20.1

**Comment by Klotzi111** [comment]
This sounds like a race condition then.

What server brand are you running? vanilla, paper, spigot?
Does the server have compression enabled (`network-compression-threshold` in `server.properties`)?
Is the server in online or offline mode?

Maybe I can reproduce the problem if I have this info.

**Comment by Apocritas99** [comment]
I tried in my localhost and in a paper server, both same issue, sometimes the bot connects when I try a lot of times, but it does nothing an disconnects after a few seconds.

**Comment by Klotzi111** [comment]
> sometimes the bot connects when I try a lot of times

Typical for a race condition. Sadly I can not reproduce this. So I can not fix it. We need to add a lot of logs to be able to see whats going on. But logging might take so much time that the race condition gets healed. Race conditions are tough.

The old version (from nuget) had the login process less optimized which might made the race condition so unlikely it worked :D

What system are you running this on? Processor? OS? Release or Debug Build? DotNet Version (exact)?

**Comment by Klotzi111** [comment]
It seems that encryption handling is broken. I will look into this. But in the mean time you can try using an offline bot (on an offline server of course) and see if that works for you. Because encryption is only used in online mode.
Use the `OfflineSession` method on the `BotBuilder` for that. The README file of the repo has this as an example.

Thanks for reporting.

**Comment by Klotzi111** [comment]
I fixed the problem. You can use the main branch of my [forked repo](https://github.com/Klotzi111/MineSharp). It should work now.
Please reply if it still does not work with that branch.

**Comment by Apocritas99** [comment]
i tried with your repo and got the following error

```
2024-08-16 17:30:12.4170|INFO|MineSharp.Protocol.MinecraftClient|Connected, starting handshake...
2024-08-16 17:30:12.4855|DEBUG|MineSharp.Protocol.MinecraftStream|Enabling encryption.
2024-08-16 17:30:13.2211|DEBUG|MineSharp.Protocol.Packets.Handlers.LoginPacketHandler|Enabling compression, threshold = 256.
2024-08-16 17:30:13.2211|ERROR|MineSharp.Protocol.MinecraftClient|Encountered exception while dispatching packet SB_Configuration_Settings|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Frozen.FrozenDictionary`2.get_Item(TKey key)
   at MineSharp.Data.Protocol.ProtocolData.GetPacketId(PacketType type) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Data\MineSharp.Data\Protocol\ProtocolData.cs:line 25
   at MineSharp.Protocol.MinecraftClient.DispatchPacket(IPacket packet) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\MinecraftClient.cs:line 584
   at MineSharp.Protocol.MinecraftClient.SendPackets() in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\MinecraftClient.cs:line 559
2024-08-16 17:30:13.2412|WARN|MineSharp.Protocol.MinecraftClient|An packet handler for packet of type CB_Login_Success threw an exception.|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Frozen.FrozenDictionary`2.get_Item(TKey key)
   at MineSharp.Data.Protocol.ProtocolData.GetPacketId(PacketType type) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Data\MineSharp.Data\Protocol\ProtocolData.cs:line 25
   at MineSharp.Protocol.MinecraftClient.DispatchPacket(IPacket packet) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\MinecraftClient.cs:line 584
   at MineSharp.Protocol.MinecraftClient.SendPackets() in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\MinecraftClient.cs:line 559
   at MineSharp.Protocol.MinecraftClient.SendPacket(IPacket packet, CancellationToken cancellation) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\MinecraftClient.cs:line 289
   at MineSharp.Protocol.Packets.Handlers.PlayPacketHandler.StateEntered() in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\Packets\Handlers\PlayPacketHandler.cs:line 27
   at MineSharp.Protocol.MinecraftClient.ChangeGameState(GameState next) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\MinecraftClient.cs:line 444
   at MineSharp.Protocol.Packets.Handlers.LoginPacketHandler.HandleLoginSuccess(LoginSuccessPacket packet) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\Packets\Handlers\LoginPacketHandler.cs:line 128
   at MineSharp.Protocol.MinecraftClient.HandleIncomingPacket(PacketType packetType, PacketBuffer buffer) in D:\Weas\Repos\C#\MyMineSharp\Klotzi\MineSharp\Components\MineSharp.Protocol\MinecraftClient.cs:line 710
```

**Comment by psu-de** [comment]
It will work on 1.20.4. 
This exception is thrown because we send a packet used in 1.20.4 in all versions before. 
I already fixed it on this main branch, however this branch doesn't have @Klotzi111's changes to the encryption.

**Comment by Klotzi111** [comment]
Ok so the encryption problem is gone.
I messed up that there are 2 different `ClientInformationPacket`s one for Play and one for Configuration.
But I fixed it now.
Please try again

**Comment by Klotzi111** [comment]
Oh we double fixed it :D
I like my fix better because I depend on the GameState rather than the version. But yours works too

**Comment by Apocritas99** [comment]
now it works good guys
